name: game_map
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  path_drawing: ^1.0.1
  talker: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/map_tiles/row-1-column-1.jpg
    - assets/map_tiles/row-1-column-2.jpg
    - assets/map_tiles/row-1-column-3.jpg
    - assets/map_tiles/row-1-column-4.jpg
    - assets/map_tiles/row-1-column-5.jpg
    - assets/map_tiles/row-1-column-6.jpg
    - assets/map_tiles/row-1-column-7.jpg
    - assets/map_tiles/row-1-column-8.jpg
    - assets/map_tiles/row-1-column-9.jpg
    - assets/map_tiles/row-1-column-10.jpg
    - assets/fullmap.jpg
    - assets/mock_path.png
    - assets/done_lvl.png
    - assets/done_lvl_1star.png
    - assets/done_lvl_2star.png
    - assets/undone_lvl.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
